"""
Package a synthesized kernel as reusable RTL along with a manifest
with metrics describing how to blackbox it for Catapult.
"""
import yaml

from tessera.models.common import is_fpga
from tessera.parser.verilog import parse_verilog
from tessera.parser.metrics.catapult import (parse_catapult_ccore,
                                     parse_catapult,
                                     parse_catapult_fpga)

# Where SCVerify puts the design under test, relative to its testbench
SCVERIFY_DUT = "scverify_top/rtl/dut_inst"


def find_sdc(design, kernel, combinational):
    """
    Find the SDC file generated by Catapult
    Its location varies depending on whether 
    the kernel is combinational or sequential.
    """
    catapult_dir = design.build_dir / "Catapult"
    if not combinational:
        return catapult_dir / f"{kernel.name}.v1" / "concat_rtl.v.dc.sdc"

    # A CCORE sits inside a clocked wrapper, whose constraints name the clock
    solutions = sorted((catapult_dir / "td_ccore_solutions").glob(f"{kernel.name}_*"))
    if not solutions:
        raise Exception(f"No CCORE solution for '{kernel.name}' in {catapult_dir}")
    return solutions[0] / "rtl.v.dc.sdc"


def dut_path(modules, module):
    """
    Where the wrapper holds the module PrimePower links, as SCVerify sees it.
    Catapult names that instance itself and nests it differently per design,
    so the parsed hierarchy is walked for it rather than assumed.
    This allows for us to find the correct DUT path in a robust fashion.
    """
    path = []
    while True:
        # The module that instantiates this one, and under what name
        holder = next(((m["name"], i["inst"]) for m in modules
                       for i in m["instances"] if i["module"] == module), None)
        if holder is None:
            break
        module, inst = holder
        path.append(inst)

    return "/".join([SCVERIFY_DUT, *reversed(path)])


def write_package(design, kernel, combinational):
    """
    Write the kernel's RTL and manifest into the design's package dir
    """
    package_dir = design.build_dir / "package"
    package_dir.mkdir(parents=True, exist_ok=True)

    # Concat RTL keeps all dependencies in one file
    rtl = design.build_dir / "Catapult" / f"{kernel.name}.v1" / "concat_rtl.v"
    (package_dir / f"{kernel.name}.v").write_text(rtl.read_text())

    sdc = find_sdc(design, kernel, combinational)
    if sdc.exists():
        (package_dir / f"{kernel.name}.sdc").write_text(sdc.read_text())

    modules = parse_verilog(rtl)

    # For combinational kernels we use the module which is named after the kernel
    # For sequential kernels we use the last/top module
    module = kernel.name if combinational else modules[-1]["name"]
    ports = next(m["ports"] for m in modules if m["name"] == module)

    # A CCORE reports its own row in the BOM, apart from the wrapper's totals
    if combinational:
        metrics = parse_catapult_ccore(design, kernel)
    else:
        metrics = parse_catapult(design)
    if is_fpga(design.design["tech_type"]):
        metrics.update(parse_catapult_fpga(design))

    manifest = {
        "kernel": kernel.name,
        "module": module,
        "rtl": f"{kernel.name}.v",
        "sdc": f"{kernel.name}.sdc" if sdc.exists() else None,
        "combinational": combinational,
        "ports": ports,
        "dut_path": dut_path(modules, module),
        "params": design.design,
        **metrics,
    }

    (package_dir / "manifest.yaml").write_text(yaml.safe_dump(manifest, sort_keys=False))


def update_manifest(design, **results):
    """
    For updating the manifest with metrics from later steps 
    (e.g. Design Compiler, PrimePower, etc.)
    """
    path = design.build_dir / "package" / "manifest.yaml"
    manifest = yaml.safe_load(path.read_text())
    manifest.update(results)
    path.write_text(yaml.safe_dump(manifest, sort_keys=False))
    return manifest
