#!/usr/bin/env python3
import argparse
import csv
import json
from pathlib import Path

from naming_short import encoder


def parse_metric_table(path):
    metrics = []
    header = None
    in_general = False

    with path.open(newline="") as f:
        for row in csv.reader(f):
            stripped = [c.strip() for c in row]

            if not any(stripped):
                if in_general and metrics:
                    break
                header = None
                continue

            if stripped[0] == "General":
                in_general = True
                header = None
                continue

            if not in_general:
                continue

            if "Latency Cycle" in stripped and "Area" in stripped:
                header = stripped
                continue

            if not header or len(stripped) < len(header):
                continue

            sol_name = stripped[0]
            if not sol_name or sol_name in ("General", "Run Time"):
                continue

            row_metrics = {}
            for idx, name in enumerate(header):
                if name:
                    row_metrics[name] = stripped[idx] if idx < len(stripped) else ""
            row_metrics["Solution"] = sol_name
            metrics.append(row_metrics)

    return metrics[0] if metrics else {}


def format_area(area):
    if not area:
        return "N/A"
    try:
        return f"{float(area):.3f}"
    except ValueError:
        return area


def main():
    parser = argparse.ArgumentParser(
        description="Summarize NTT Catapult table CSVs for generated sweep configs."
    )
    parser.add_argument(
        "--configs",
        default="tmp_configs/ntt_configs.json",
        help="Sweep config JSON generated by run.py.",
    )
    parser.add_argument(
        "--catapult-dir",
        default="lvl2/ntt/Catapult",
        help="Directory containing Catapult table_*.csv files.",
    )
    args = parser.parse_args()

    config_path = Path(args.configs)
    catapult_dir = Path(args.catapult_dir)

    if not config_path.exists():
        raise FileNotFoundError(f"Missing config JSON: {config_path}")

    data = json.loads(config_path.read_text())
    suffix = data.get("control_flags", {}).get("PROJECT_NAME_SUFFIX", "")

    rows = []
    for cfg in data.get("sweep_configs", []):
        sweep_key = encoder(cfg)
        if suffix:
            sweep_key = f"{sweep_key}__{suffix}"

        csv_path = catapult_dir / f"table_{sweep_key}.csv"
        metrics = parse_metric_table(csv_path) if csv_path.exists() else {}

        rows.append(
            {
                "ntt_len": cfg.get("NTT_LEN", ""),
                "unroll": cfg.get("NTT_BF_UNROLL", ""),
                "csv": csv_path,
                "exists": csv_path.exists(),
                "latency": metrics.get("Latency Cycle", ""),
                "area": metrics.get("Area", ""),
            }
        )

    print("\nGenerated/expected Catapult table CSVs:")
    for row in rows:
        status = "found" if row["exists"] else "missing"
        print(f"  [{status}] {row['csv']}")

    print("\nNTT sweep summary:")
    print(f"{'NTT_LEN':>8} {'UNROLL':>8} {'LATENCY_CYCLES':>15} {'AREA':>15}")
    print(f"{'-' * 8} {'-' * 8} {'-' * 15} {'-' * 15}")
    for row in rows:
        latency = row["latency"] if row["latency"] else "N/A"
        area = format_area(row["area"])
        print(f"{row['ntt_len']:>8} {row['unroll']:>8} {latency:>15} {area:>15}")


if __name__ == "__main__":
    main()
