import logging
import os
import subprocess
import time
from pathlib import Path

from tessera.config import RunConfig
from tessera.flows.base import Flow
from tessera.flows.gls.makefile import gen_gls_makefile
from tessera.helper import archive_run, get_design_dir_name, log_elapsed


class GLS(Flow):
    """
    Gate-Level Simulation (GLS): 
        Run the RTL testbench against the synthesized netlist.

    Catapult generates a makefile listing the Verilog that SCVerify compiles. 
    For gate level simulation, we reuse all of it and swap one entry: 
    the design under test becomes the netlist Design Compiler produced.
    """
    name = "Gate level simulation"
    stage = "gls"

    def run(self, design, kernel_ctx):
        design_name = get_design_dir_name(design, kernel_ctx.kernel)
        design_build_dir = Path(kernel_ctx.kernel_build_dir, design_name)
        start_time = time.time()

        conf = RunConfig.load()
        tech = conf.tech[design["tech_type"]]
        if not tech.lib_verilog:
            raise Exception(f"'{design['tech_type']}' has no lib_verilog, so its "
                            f"cells cannot be simulated")

        archive_run(design_build_dir, dirs=("gls",))
        gls_dir = design_build_dir / "gls"

        makefile, combinational = gen_gls_makefile(
            kernel_ctx.kernel, design_build_dir, gls_dir,
            str(Path(tech.lib_verilog).expanduser()), tech.lib_verilog_defines)

        kind = "combinational" if combinational else "sequential"
        logging.info(f"Running gate level simulation for {design_name} ({kind})")

        env = {
            **os.environ,
            # Questa reads its own license variable
            "SALT_LICENSE_SERVER": os.environ.get("MGLS_LICENSE_FILE", ""),
            "QSIM_HOME": str(Path(conf.tools["questa"]).expanduser()),
        }

        # TARGET is where the compiled libraries land. 
        # We override it to keep the libraries out of the Catapult project.
        # Because the original Makefile was generated by Catapult.
        solution = Path(design_build_dir, "Catapult", f"{kernel_ctx.kernel}.v1")
        target = os.path.relpath(gls_dir.resolve(), solution.resolve())

        log_path = design_build_dir / "logs" / "gls.tessera.log"
        log_path.parent.mkdir(parents=True, exist_ok=True)
        with log_path.open("w") as log:
            subprocess.run(
                ["make", "-f", str(makefile.resolve()), "SIMTOOL=msim",
                 f"TARGET={target}",
                 f"CCS_VCD_FILE={(gls_dir / 'gate.vcd').resolve()}", "sim"],
                cwd=solution,
                env=env,
                stdout=log,
                stderr=subprocess.STDOUT,
            )

        # SCVerify reports the comparison itself, and make exits 0 either way
        passed = "Simulation PASSED" in log_path.read_text()
        return log_elapsed(self.name, design_name, 0 if passed else 1, start_time)
